graph TD
    CBACT01C -->|CALL| CEE3ABD
    CBACT01C -->|CALL| COBDATFT
    CBACT02C -->|CALL| CEE3ABD
    CBACT03C -->|CALL| CEE3ABD
    CBACT04C -->|CALL| CEE3ABD
    CBCUS01C -->|CALL| CEE3ABD
    CBEXPORT -->|CALL| CEE3ABD
    CBIMPORT -->|CALL| CEE3ABD
    CBSTM03A -->|CALL| CBSTM03B
    CBSTM03A -->|CALL| CEE3ABD
    CBTRN01C -->|CALL| CEE3ABD
    CBTRN02C -->|CALL| CEE3ABD
    CBTRN03C -->|CALL| CEE3ABD
    COACTUPC -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COACTVWC -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COADM01C -->|CICS_XCTL| CDEMO-ADMIN-OPT-PGMNAME(WS-OPTION
    COADM01C -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COBIL00C -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COBSWAIT -->|CALL| MVSWAIT
    COCRDLIC -->|CICS_XCTL| CCARD-NEXT-PROG
    COCRDLIC -->|CICS_XCTL| LIT-MENUPGM
    COCRDSLC -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COCRDUPC -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COMEN01C -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COMEN01C -->|CICS_XCTL| CDEMO-MENU-OPT-PGMNAME(WS-OPTION
    CORPT00C -->|CALL| CSUTLDTC
    CORPT00C -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COSGN00C -->|CICS_XCTL| COMEN01C
    COSGN00C -->|CICS_XCTL| COADM01C
    COTRN00C -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COTRN01C -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COTRN02C -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COTRN02C -->|CALL| CSUTLDTC
    COUSR00C -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COUSR01C -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COUSR02C -->|CICS_XCTL| CDEMO-TO-PROGRAM
    COUSR03C -->|CICS_XCTL| CDEMO-TO-PROGRAM
    CSUTLDTC -->|CALL| CEEDAYS