graph LR
    CBACT01C -->|READ| ACCTFILE_FILE[("ACCTFILE-FILE")]
    CBACT01C -->|OPEN_INPUT| ACCTFILE_FILE[("ACCTFILE-FILE")]
    CBACT01C -->|CLOSE| ACCTFILE_FILE[("ACCTFILE-FILE")]
    CBACT01C -->|WRITE| ARR_ARRAY_REC[("ARR-ARRAY-REC")]
    CBACT01C -->|OPEN_OUTPUT| ARRY_FILE[("ARRY-FILE")]
    CBACT01C -->|WRITE| OUT_ACCT_REC[("OUT-ACCT-REC")]
    CBACT01C -->|OPEN_OUTPUT| OUT_FILE[("OUT-FILE")]
    CBACT01C -->|WRITE| VBR_REC[("VBR-REC")]
    CBACT01C -->|OPEN_OUTPUT| VBRC_FILE[("VBRC-FILE")]
    CBACT02C -->|READ| CARDFILE_FILE[("CARDFILE-FILE")]
    CBACT02C -->|OPEN_INPUT| CARDFILE_FILE[("CARDFILE-FILE")]
    CBACT02C -->|CLOSE| CARDFILE_FILE[("CARDFILE-FILE")]
    CBACT03C -->|READ| XREFFILE_FILE[("XREFFILE-FILE")]
    CBACT03C -->|OPEN_INPUT| XREFFILE_FILE[("XREFFILE-FILE")]
    CBACT03C -->|CLOSE| XREFFILE_FILE[("XREFFILE-FILE")]
    CBACT04C -->|OPEN_I-O| ACCOUNT_FILE[("ACCOUNT-FILE")]
    CBACT04C -->|READ| ACCOUNT_FILE[("ACCOUNT-FILE")]
    CBACT04C -->|CLOSE| ACCOUNT_FILE[("ACCOUNT-FILE")]
    CBACT04C -->|CLOSE| DISCGRP_FILE[("DISCGRP-FILE")]
    CBACT04C -->|READ| DISCGRP_FILE[("DISCGRP-FILE")]
    CBACT04C -->|OPEN_INPUT| DISCGRP_FILE[("DISCGRP-FILE")]
    CBACT04C -->|REWRITE| FD_ACCTFILE_REC[("FD-ACCTFILE-REC")]
    CBACT04C -->|WRITE| FD_TRANFILE_REC[("FD-TRANFILE-REC")]
    CBACT04C -->|CLOSE| TCATBAL_FILE[("TCATBAL-FILE")]
    CBACT04C -->|OPEN_INPUT| TCATBAL_FILE[("TCATBAL-FILE")]
    CBACT04C -->|READ| TCATBAL_FILE[("TCATBAL-FILE")]
    CBACT04C -->|OPEN_OUTPUT| TRANSACT_FILE[("TRANSACT-FILE")]
    CBACT04C -->|CLOSE| TRANSACT_FILE[("TRANSACT-FILE")]
    CBACT04C -->|READ| XREF_FILE[("XREF-FILE")]
    CBACT04C -->|CLOSE| XREF_FILE[("XREF-FILE")]
    CBACT04C -->|OPEN_INPUT| XREF_FILE[("XREF-FILE")]
    CBCUS01C -->|READ| CUSTFILE_FILE[("CUSTFILE-FILE")]
    CBCUS01C -->|OPEN_INPUT| CUSTFILE_FILE[("CUSTFILE-FILE")]
    CBCUS01C -->|CLOSE| CUSTFILE_FILE[("CUSTFILE-FILE")]
    CBEXPORT -->|OPEN_INPUT| ACCOUNT_INPUT[("ACCOUNT-INPUT")]
    CBEXPORT -->|READ| ACCOUNT_INPUT[("ACCOUNT-INPUT")]
    CBEXPORT -->|CLOSE| ACCOUNT_INPUT[("ACCOUNT-INPUT")]
    CBEXPORT -->|READ| CARD_INPUT[("CARD-INPUT")]
    CBEXPORT -->|CLOSE| CARD_INPUT[("CARD-INPUT")]
    CBEXPORT -->|OPEN_INPUT| CARD_INPUT[("CARD-INPUT")]
    CBEXPORT -->|OPEN_INPUT| CUSTOMER_INPUT[("CUSTOMER-INPUT")]
    CBEXPORT -->|READ| CUSTOMER_INPUT[("CUSTOMER-INPUT")]
    CBEXPORT -->|CLOSE| CUSTOMER_INPUT[("CUSTOMER-INPUT")]
    CBEXPORT -->|OPEN_OUTPUT| EXPORT_OUTPUT[("EXPORT-OUTPUT")]
    CBEXPORT -->|CLOSE| EXPORT_OUTPUT[("EXPORT-OUTPUT")]
    CBEXPORT -->|WRITE| EXPORT_OUTPUT_RECORD[("EXPORT-OUTPUT-RECORD")]
    CBEXPORT -->|OPEN_INPUT| TRANSACTION_INPUT[("TRANSACTION-INPUT")]
    CBEXPORT -->|READ| TRANSACTION_INPUT[("TRANSACTION-INPUT")]
    CBEXPORT -->|CLOSE| TRANSACTION_INPUT[("TRANSACTION-INPUT")]
    CBEXPORT -->|OPEN_INPUT| XREF_INPUT[("XREF-INPUT")]
    CBEXPORT -->|READ| XREF_INPUT[("XREF-INPUT")]
    CBEXPORT -->|CLOSE| XREF_INPUT[("XREF-INPUT")]
    CBIMPORT -->|CLOSE| ACCOUNT_OUTPUT[("ACCOUNT-OUTPUT")]
    CBIMPORT -->|OPEN_OUTPUT| ACCOUNT_OUTPUT[("ACCOUNT-OUTPUT")]
    CBIMPORT -->|WRITE| ACCOUNT_RECORD[("ACCOUNT-RECORD")]
    CBIMPORT -->|OPEN_OUTPUT| CARD_OUTPUT[("CARD-OUTPUT")]
    CBIMPORT -->|CLOSE| CARD_OUTPUT[("CARD-OUTPUT")]
    CBIMPORT -->|WRITE| CARD_RECORD[("CARD-RECORD")]
    CBIMPORT -->|WRITE| CARD_XREF_RECORD[("CARD-XREF-RECORD")]
    CBIMPORT -->|CLOSE| CUSTOMER_OUTPUT[("CUSTOMER-OUTPUT")]
    CBIMPORT -->|OPEN_OUTPUT| CUSTOMER_OUTPUT[("CUSTOMER-OUTPUT")]
    CBIMPORT -->|WRITE| CUSTOMER_RECORD[("CUSTOMER-RECORD")]
    CBIMPORT -->|OPEN_OUTPUT| ERROR_OUTPUT[("ERROR-OUTPUT")]
    CBIMPORT -->|CLOSE| ERROR_OUTPUT[("ERROR-OUTPUT")]
    CBIMPORT -->|WRITE| ERROR_OUTPUT_RECORD[("ERROR-OUTPUT-RECORD")]
    CBIMPORT -->|CLOSE| EXPORT_INPUT[("EXPORT-INPUT")]
    CBIMPORT -->|OPEN_INPUT| EXPORT_INPUT[("EXPORT-INPUT")]
    CBIMPORT -->|READ| EXPORT_INPUT[("EXPORT-INPUT")]
    CBIMPORT -->|WRITE| TRAN_RECORD[("TRAN-RECORD")]
    CBIMPORT -->|CLOSE| TRANSACTION_OUTPUT[("TRANSACTION-OUTPUT")]
    CBIMPORT -->|OPEN_OUTPUT| TRANSACTION_OUTPUT[("TRANSACTION-OUTPUT")]
    CBIMPORT -->|CLOSE| XREF_OUTPUT[("XREF-OUTPUT")]
    CBIMPORT -->|OPEN_OUTPUT| XREF_OUTPUT[("XREF-OUTPUT")]
    CBSTM03A -->|WRITE| FD_HTMLFILE_REC[("FD-HTMLFILE-REC")]
    CBSTM03A -->|WRITE| FD_STMTFILE_REC[("FD-STMTFILE-REC")]
    CBSTM03A -->|CLOSE| STMT_FILE[("STMT-FILE")]
    CBSTM03A -->|OPEN_OUTPUT| STMT_FILE[("STMT-FILE")]
    CBSTM03B -->|OPEN_INPUT| ACCT_FILE[("ACCT-FILE")]
    CBSTM03B -->|CLOSE| ACCT_FILE[("ACCT-FILE")]
    CBSTM03B -->|READ| ACCT_FILE[("ACCT-FILE")]
    CBSTM03B -->|READ| CUST_FILE[("CUST-FILE")]
    CBSTM03B -->|CLOSE| CUST_FILE[("CUST-FILE")]
    CBSTM03B -->|OPEN_INPUT| CUST_FILE[("CUST-FILE")]
    CBSTM03B -->|READ| TRNX_FILE[("TRNX-FILE")]
    CBSTM03B -->|CLOSE| TRNX_FILE[("TRNX-FILE")]
    CBSTM03B -->|OPEN_INPUT| TRNX_FILE[("TRNX-FILE")]
    CBSTM03B -->|READ| XREF_FILE[("XREF-FILE")]
    CBSTM03B -->|CLOSE| XREF_FILE[("XREF-FILE")]
    CBSTM03B -->|OPEN_INPUT| XREF_FILE[("XREF-FILE")]
    CBTRN01C -->|OPEN_INPUT| ACCOUNT_FILE[("ACCOUNT-FILE")]
    CBTRN01C -->|CLOSE| ACCOUNT_FILE[("ACCOUNT-FILE")]
    CBTRN01C -->|READ| ACCOUNT_FILE[("ACCOUNT-FILE")]
    CBTRN01C -->|CLOSE| CARD_FILE[("CARD-FILE")]
    CBTRN01C -->|OPEN_INPUT| CARD_FILE[("CARD-FILE")]
    CBTRN01C -->|OPEN_INPUT| CUSTOMER_FILE[("CUSTOMER-FILE")]
    CBTRN01C -->|CLOSE| CUSTOMER_FILE[("CUSTOMER-FILE")]
    CBTRN01C -->|READ| DALYTRAN_FILE[("DALYTRAN-FILE")]
    CBTRN01C -->|OPEN_INPUT| DALYTRAN_FILE[("DALYTRAN-FILE")]
    CBTRN01C -->|CLOSE| DALYTRAN_FILE[("DALYTRAN-FILE")]
    CBTRN01C -->|OPEN_INPUT| TRANSACT_FILE[("TRANSACT-FILE")]
    CBTRN01C -->|CLOSE| TRANSACT_FILE[("TRANSACT-FILE")]
    CBTRN01C -->|READ| XREF_FILE[("XREF-FILE")]
    CBTRN01C -->|OPEN_INPUT| XREF_FILE[("XREF-FILE")]
    CBTRN01C -->|CLOSE| XREF_FILE[("XREF-FILE")]
    CBTRN02C -->|CLOSE| ACCOUNT_FILE[("ACCOUNT-FILE")]
    CBTRN02C -->|READ| ACCOUNT_FILE[("ACCOUNT-FILE")]
    CBTRN02C -->|OPEN_I-O| ACCOUNT_FILE[("ACCOUNT-FILE")]
    CBTRN02C -->|OPEN_OUTPUT| DALYREJS_FILE[("DALYREJS-FILE")]
    CBTRN02C -->|CLOSE| DALYREJS_FILE[("DALYREJS-FILE")]
    CBTRN02C -->|CLOSE| DALYTRAN_FILE[("DALYTRAN-FILE")]
    CBTRN02C -->|READ| DALYTRAN_FILE[("DALYTRAN-FILE")]
    CBTRN02C -->|OPEN_INPUT| DALYTRAN_FILE[("DALYTRAN-FILE")]
    CBTRN02C -->|REWRITE| FD_ACCTFILE_REC[("FD-ACCTFILE-REC")]
    CBTRN02C -->|WRITE| FD_REJS_RECORD[("FD-REJS-RECORD")]
    CBTRN02C -->|WRITE| FD_TRAN_CAT_BAL_RECORD[("FD-TRAN-CAT-BAL-RECORD")]
    CBTRN02C -->|REWRITE| FD_TRAN_CAT_BAL_RECORD[("FD-TRAN-CAT-BAL-RECORD")]
    CBTRN02C -->|WRITE| FD_TRANFILE_REC[("FD-TRANFILE-REC")]
    CBTRN02C -->|OPEN_I-O| TCATBAL_FILE[("TCATBAL-FILE")]
    CBTRN02C -->|READ| TCATBAL_FILE[("TCATBAL-FILE")]
    CBTRN02C -->|CLOSE| TCATBAL_FILE[("TCATBAL-FILE")]
    CBTRN02C -->|CLOSE| TRANSACT_FILE[("TRANSACT-FILE")]
    CBTRN02C -->|OPEN_OUTPUT| TRANSACT_FILE[("TRANSACT-FILE")]
    CBTRN02C -->|READ| XREF_FILE[("XREF-FILE")]
    CBTRN02C -->|CLOSE| XREF_FILE[("XREF-FILE")]
    CBTRN02C -->|OPEN_INPUT| XREF_FILE[("XREF-FILE")]
    CBTRN03C -->|CLOSE| DATE_PARMS_FILE[("DATE-PARMS-FILE")]
    CBTRN03C -->|OPEN_INPUT| DATE_PARMS_FILE[("DATE-PARMS-FILE")]
    CBTRN03C -->|READ| DATE_PARMS_FILE[("DATE-PARMS-FILE")]
    CBTRN03C -->|WRITE| FD_REPTFILE_REC[("FD-REPTFILE-REC")]
    CBTRN03C -->|CLOSE| REPORT_FILE[("REPORT-FILE")]
    CBTRN03C -->|OPEN_OUTPUT| REPORT_FILE[("REPORT-FILE")]
    CBTRN03C -->|READ| TRANCATG_FILE[("TRANCATG-FILE")]
    CBTRN03C -->|CLOSE| TRANCATG_FILE[("TRANCATG-FILE")]
    CBTRN03C -->|OPEN_INPUT| TRANCATG_FILE[("TRANCATG-FILE")]
    CBTRN03C -->|CLOSE| TRANSACT_FILE[("TRANSACT-FILE")]
    CBTRN03C -->|OPEN_INPUT| TRANSACT_FILE[("TRANSACT-FILE")]
    CBTRN03C -->|READ| TRANSACT_FILE[("TRANSACT-FILE")]
    CBTRN03C -->|CLOSE| TRANTYPE_FILE[("TRANTYPE-FILE")]
    CBTRN03C -->|OPEN_INPUT| TRANTYPE_FILE[("TRANTYPE-FILE")]
    CBTRN03C -->|READ| TRANTYPE_FILE[("TRANTYPE-FILE")]
    CBTRN03C -->|CLOSE| XREF_FILE[("XREF-FILE")]
    CBTRN03C -->|OPEN_INPUT| XREF_FILE[("XREF-FILE")]
    CBTRN03C -->|READ| XREF_FILE[("XREF-FILE")]
    COACTUPC -->|REWRITE| FILE[("FILE")]
    COCRDUPC -->|REWRITE| FILE[("FILE")]