graph TD
    CBEXPORT["JOB:CBEXPORT"] --> CBEXPORT["CBEXPORT"]
    CBIMPORT["JOB:CBIMPORT"] --> CBIMPORT["CBIMPORT"]
    CREASTMT["JOB:CREASTMT"] --> CBSTM03A["CBSTM03A"]
    INTCALC["JOB:INTCALC"] --> CBACT04C["CBACT04C"]
    POSTTRAN["JOB:POSTTRAN"] --> CBTRN02C["CBTRN02C"]
    READACCT["JOB:READACCT"] --> CBACT01C["CBACT01C"]
    READCARD["JOB:READCARD"] --> CBACT02C["CBACT02C"]
    READCUST["JOB:READCUST"] --> CBCUS01C["CBCUS01C"]
    READXREF["JOB:READXREF"] --> CBACT03C["CBACT03C"]
    TRANREPT["JOB:TRANREPT"] --> CBTRN03C["CBTRN03C"]