graph LR
    COACTUPC -->|XCTL:CAUP| CDEMO-TO-PROGRAM
    COACTVWC -->|XCTL:CAVW| CDEMO-TO-PROGRAM
    COADM01C -->|XCTL:CA00| CDEMO-ADMIN-OPT-PGMNAME(WS-OPTION
    COADM01C -->|XCTL:CA00| CDEMO-TO-PROGRAM
    COBIL00C -->|XCTL:CB00| CDEMO-TO-PROGRAM
    COCRDLIC -->|XCTL:CCLI| LIT-MENUPGM
    COCRDLIC -->|XCTL:CCLI| CCARD-NEXT-PROG
    COCRDSLC -->|XCTL:CCDL| CDEMO-TO-PROGRAM
    COCRDUPC -->|XCTL:CCUP| CDEMO-TO-PROGRAM
    COMEN01C -->|XCTL:CM00| CDEMO-MENU-OPT-PGMNAME(WS-OPTION
    COMEN01C -->|XCTL:CM00| CDEMO-TO-PROGRAM
    CORPT00C -->|XCTL:CR00| CDEMO-TO-PROGRAM
    COSGN00C -->|XCTL:CC00| COMEN01C
    COSGN00C -->|XCTL:CC00| COADM01C
    COTRN00C -->|XCTL:CT00| CDEMO-TO-PROGRAM
    COTRN01C -->|XCTL:CT01| CDEMO-TO-PROGRAM
    COTRN02C -->|XCTL:CT02| CDEMO-TO-PROGRAM
    COUSR00C -->|XCTL:CU00| CDEMO-TO-PROGRAM
    COUSR01C -->|XCTL:CU01| CDEMO-TO-PROGRAM
    COUSR02C -->|XCTL:CU02| CDEMO-TO-PROGRAM
    COUSR03C -->|XCTL:CU03| CDEMO-TO-PROGRAM